version: '3.11'

services:

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - '5432'

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate && gunicorn -c gunicorn.conf.py service_desk.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "81:80"
    depends_on:
      - backend
    restart: always

volumes:
  pg_data:
