# Generated by Django 5.1.3 on 2024-11-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("support_operator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                ("request_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("in_progress", "В работе"),
                            ("closed", "Закрыто"),
                        ],
                        default="new",
                        max_length=30,
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("user_email", models.CharField(max_length=255)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="support_operator.supportoperator",
                    ),
                ),
            ],
            options={
                "db_table": "user_requests",
                "ordering": ["-date_create"],
            },
        ),
    ]
