# Generated by Django 5.1.3 on 2024-11-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupportOperator",
            fields=[
                ("operator_id", models.IntegerField(primary_key=True, serialize=False)),
                ("operator_name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "support_operator",
                "ordering": ["operator_id"],
            },
        ),
    ]
