# Generated by Django 5.1.3 on 2024-11-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_requests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sort", models.IntegerField()),
                ("sender_id", models.CharField(max_length=50)),
                ("sender_type", models.CharField(max_length=30)),
                ("title", models.TextField()),
                ("text", models.TextField()),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="user_requests.userrequest",
                    ),
                ),
            ],
            options={
                "db_table": "request_messages",
            },
        ),
    ]
